### ISSUE TITLE
A RecipeId that is too long will break the SearchById feature

### ISSUE THREAD

**Issue by jaeyonglee3** [pratzyushd/csc207-course-project#30]
Here is the expected output after an invalid recipe Id being searched for:

<img width="448" alt="Screenshot 2023-11-24 at 7 59 59 PM" src="https://github.com/pratzyushd/csc207-course-project/assets/73498725/fb382f12-b6a7-4829-a2bf-122d3bc4701a">

However, if the recipe ID that is inputted is too long, this occurs internally and the program breaks. This has to do with how we are changing the input String to an int. We can add something that catches if the input string is simply too long. The fix should not be complicated.

<img width="1006" alt="Screenshot 2023-11-24 at 8 00 49 PM" src="https://github.com/pratzyushd/csc207-course-project/assets/73498725/37b9fb1a-bc60-4bdf-9929-53f595f88cfe">

**Comment by pratzyushd** [comment]
More concretely, our fix could be as follows:

- Have the use case interactor carry out the validation before casting to an integer
- Modify the `prepareFailView` method to take a `String` instead of `OutputData`, and have this string be the relevant error message
    - This means that our interactor can now pass in the relevant string (i.e. "Recipe not found", or "Invalid ID" depending on the actual error) and the presenter can display that instead.
